### ISSUE TITLE
Support for react-native-windows

### ISSUE THREAD

**Issue by exotexot** [birdofpreyru/react-native-static-server#10]
It's great to see that someone tries to give new life to this module.

I was wondering if there's a chance that would also consider using a working version for Windows.
Here (https://github.com/exotexot/react-native-static-server/tree/windows) I'm running a version which is largely based on Julien's version found here: https://github.com/futurepress/react-native-static-server/pull/19

The windows version should use a c++ static server. Here I have no idea which library supports windows / c++ and can possibly replace the older c# / Restup version. 

Does anyone have an idea which Windows library could be used?

**Comment by birdofpreyru** [comment]
Hey @exotexot ,

I am open to accept PRs if you, or anybody else, is up to implement and maintain Windows support in my fork of the library. Myself I have not done any Windows-targeted development lately, nor I am having any plans in sight to do it, especially RN-based. Thus, working on supporting Windows in this library is not something I can do myself at the moment.
