### ISSUE TITLE
Error: No template named 'optional' in namespace 'std'

### ISSUE THREAD

**Issue by christophby** [birdofpreyru/react-native-static-server#109]
I cannot build the project.
Error is coming from Xcode in `ReactNativeFs.h`.

<img width="1061" alt="image" src="https://github.com/birdofpreyru/react-native-static-server/assets/12933672/679bdfe8-cca1-4ed8-8057-947a16e7643f">

> No template named 'optional' in namespace 'std'

> Cannot initialize return object of type 'int' with an rvalue of type 'id _Nullable'

* react-native 0.69.12

**Comment by birdofpreyru** [comment]
> _react-native 0.69.12_

As of now, for this library, I only test & support compatibility to the latest RN version, which is 0.74.

0.69 is old enough to not be maintained by RN project in general: https://reactnative.dev/versions

If you are into troubleshooting / patching it yourself, the C++ version is set in the library podfile here: https://github.com/birdofpreyru/react-native-static-server/blob/3dc459b10343fa560a0fc3856a710c761b5f9f2d/dr-pogodin-react-native-static-server.podspec#L114

which is applied each time you `pod install` / `pod update` it. Presumably, it works fine for latest versions of everything (RN, Xcode, _etc._), and I am not sure why it does not work for older RN. Or, perhaps, it does not work as intended, but with latest versions of everything something else enforces the correct version.

**Comment by christophby** [comment]
I'm using the latest versions
* `@dr.pogodin/react-native-static-server` 0.15.0
*` @dr.pogodin/react-native-fs` 2.25.0

But I will probably patch it, thank you!
