### ISSUE TITLE
NullPointerException in com.futurepress.staticserver.FPStaticServerModule.start

### ISSUE THREAD

**Issue by douglasjunior** [birdofpreyru/react-native-static-server#11]
Play Store is reporting NullPointerException ANRs in our app, it is affecting 12% of our Android users.

We are using v0.5.5 currently.

```
Exception java.lang.NullPointerException:
  at java.io.File.<init> (File.java:363)
  at com.futurepress.staticserver.FPStaticServerModule.start (FPStaticServerModule.java:102)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:151)
  at com.facebook.react.bridge.queue.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:329)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:226)
  at java.lang.Thread.run (Thread.java:920)
```

Any help?

**Comment by birdofpreyru** [comment]
That should be line 102 in the following code block, where static server figures out the absolute path to the root folder from which it should serve stuff:
https://github.com/birdofpreyru/react-native-static-server/blob/4a273091991bece77c1fbfc7c77617257ff06613/android/src/main/java/com/futurepress/staticserver/FPStaticServerModule.java#L98-L104

Considering it works fine for 88% of your users, I guess that is just the folder you are trying to use is protected from app access on just some devices, or for some reason you fail to correctly init the folder / move the stuff to serve in there. What folder are you trying to serve? In my projects for Android I use `RNFS.DocumentDirectoryPath`, as the README suggests, and I copy all assets to serve into that folder, and I have not seen such error so far.

**Comment by douglasjunior** [comment]
Hi @birdofpreyru , thank you for your answer.

We are using `DocumentDir` from `RNFetchBlob`:

```js
        let dirs = RNFetchBlob.fs.dirs
        let path = `${dirs.DocumentDir}/www/${rota}/build`;
        this.BlockServer = new StaticServer(port, path, {
            keepAlive: true,
            localOnly: true
        });
```

Looks like the RNFetchBlob also uses the "ctx.getFilesDir().getAbsolutePath()": https://github.com/joltup/rn-fetch-blob/blob/cf9e8843599de92031df2660d5a1da18491fa3c0/android/src/main/java/com/RNFetchBlob/RNFetchBlobFS.java#L250-L254

**Comment by birdofpreyru** [comment]
@douglasjunior I never heard of `RNFetchBlob` before, and not quite interested to familiarise myself with it now. Though, it looks like at the moment you do ` this.BlockServer = new StaticServer(port, path, {` that path you use, ``${dirs.DocumentDir}/www/${rota}/build``, does not exist yet, and that crashes the server. I wonder, probably you miss to wait till `RNFetchBlob` creates that folder, which in some cases it does faster than the server initializes, but in some cases it is a bit too slow.

**Comment by douglasjunior** [comment]
The directory exists because it is created in some previous steps when the files are downloaded and stored in this location.

**Comment by birdofpreyru** [comment]
Well, I don't know, something is still wrong with that directory. Have you noticed btw, if you hit line 102 in the server code, it means you passed in a relative path? Why? Isn't the fetch blobs directory supposed to be an absolute path?

**Comment by birdofpreyru** [comment]
Closing, as more than 30 days since the last message, and I don't think there is any related issue to fix in the library.
