### ISSUE TITLE
Could I dynamically reload assets when I update files in `fileDir` on dev mode?

### ISSUE THREAD

**Issue by hanwong** [birdofpreyru/react-native-static-server#114]
Could I dynamically reload assets when I update files in `fileDir` on dev mode?

**Comment by birdofpreyru** [comment]
It kind of always serves the current content of `fileDir`, but there are various caching features in Lighttpd, which you probably need to tune as per its [Documentation](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ConfigurationOptions), to ensure it picks up asset updates as soon as you need.

**Comment by hanwong** [comment]
> It kind of always serves the current content of `fileDir`, but there are various caching features in Lighttpd, which you probably need to tune as per its [Documentation](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ConfigurationOptions), to ensure it picks up asset updates as soon as you need.

I have tried to set some configs, but it was not work.
Could you got me to way how to set it? Many developer using this library would be front-end developer, they are not good at setting sever.

thank you

**Comment by birdofpreyru** [comment]
I see no reason to contribute my work into your project for free.

**Comment by hanwong** [comment]
I think this issue should be contain in the docs.

**Comment by birdofpreyru** [comment]
I don't see it is an issue _per se_, though I told you how to deal with it; if you lack the experience to further figure it out yourself, you have to pay somebody to do it for you :man_shrugging:

> _I think this issue should be contained in the docs of @dr.pogodin/react-native-static-server._

I think, you misunderstand the motivation of people to open-source their projects; you haven't paid much attention to the &laquo;AS IS&raquo; clause of [MIT License](https://github.com/birdofpreyru/react-native-static-server/blob/master/LICENSE.md); and perhaps haven't noticed [![](https://raw.githubusercontent.com/birdofpreyru/react-native-static-server/master/.README/sponsor.svg)](https://github.com/sponsors/birdofpreyru) button in the README :sweat_smile:

**Comment by hanwong** [comment]
i got it, i just think it need to be good to improve developer experience.
