### ISSUE TITLE
Upgrade to different underlying HTTP servers

### ISSUE THREAD

**Issue by birdofpreyru** [birdofpreyru/react-native-static-server#12]
Currently (as of version **0.6.0** of this library, and below) we depend on these underlying HTTP servers:
- [GCDWebServer](https://github.com/swisspol/GCDWebServer) on iOS - last release on Mar 15, 2020 (~2 years ago).
- [NanoHttpd Webserver](https://github.com/NanoHttpd/nanohttpd) on Android - last release on Aug 12, 2016 (~6 years ago).

Thus, the Android server looks quite abandoned at this point, and iOS one not very actively maintained / developed. Probably, we need to migrate to better / more alive alternatives, if such exist.

**Comment by exotexot** [comment]
That is a huge issue!
I'm not an expert on this, and this may be out-of-scope for this repo, but it would be AWESOME if you could decide for a embedded server solution, that works on ALL relevant platforms. Maybe something like Mongoose? It doesn't explicitly say that it works on iOS, but it does work on Android (and my personal wish: Windows / c++). 

https://github.com/cesanta/mongoose

I guess there is also something like an objective-c wrapper for mongoose.

**Comment by exotexot** [comment]
Ah, of course that is a valid point to inspect the licensing!
I just jumped into this conversation, as I had the same thoughts about outdated dependency, and I'm also looking for a suitable cross platform server solution for react native apps. lighttpd seems like a good option then :)

**Comment by rafalzawadzki** [comment]
I'm very excited to see the current development in the direction of lighttpd! Having a maintained & configurable static server setup will be a major milestone for React Native. Looking forward to 0.7 🎉
