### ISSUE TITLE
[V0.17.1] : Not building with Cmake Version 3.30.3 and 3.30.2

### ISSUE THREAD

**Issue by sambouchard-newforma** [birdofpreyru/react-native-static-server#121]
Hi,

I upgraded the library to version 0.17.1 and upgraded my cMake version to the latest(I've tested with both version 3.30.3 and 3.30.4) and having 2 differents errors:

1. After running `pod install` and running a build from xCode, I'm getting the following error(with both cMake 3.30.2 and 3.30.3) : 

`❌  /Users/runner/work/1/s/node_modules/@dr.pogodin/react-native-static-server/ios/generated/RNReactNativeStaticServerSpecJSI.h:12:10: 'ReactCommon/TurboModule.h' file not found
`

![image](https://github.com/user-attachments/assets/f5edf340-cc1b-4b1a-9fff-60b581ea7294)

2. After digging up online a little bit and trying to run `RCT_NEW_ARCH_ENABLED=1 pod install` to enable the new architecture( with TurboModules) : 

`❌  /Users/runner/work/1/s/ios/Pods/Headers/Public/RCT-Folly/folly/functional/Invoke.h:22:10: 'boost/preprocessor/control/expr_iif.hpp' file not found
`

![image](https://github.com/user-attachments/assets/6e0a5981-91f5-41dc-95c9-44b3fa64a5dc)
All of the boost assets seems to be absent from the pods folder : 
![image](https://github.com/user-attachments/assets/eb502d20-e3f6-4642-b38e-2bc4b8908afd)

We are still able to build our project version 0.9.2 of react-native-server and cMake version 3.27.5 but that requires us to install this particular version of cMake on every-one of our CI/CD pipelines wich is time consuming and we would like to use cMake 3.30.3 wich is the version that comes bundled with the Microsoft hosted agent.

**Comment by birdofpreyru** [comment]
`react-native-server@0.9.2` supports React Native v0.72; the latest `react-native-server@0.17.1` supports the latest React Native 0.75. Looking at your errors, and considering that v0.9.2 works for you, I guess you haven't correctly upgraded your project from RN@0.72 to RN@0.75, and there is no issue with the library.

**Comment by sambouchard-newforma** [comment]
Great, I will come back to this thread when bumping React-Native version to 0.75, thanx so much @birdofpreyru and have a blessed day!
