### ISSUE TITLE
Multiple resources in one server

### ISSUE THREAD

**Issue by Phong-TH** [birdofpreyru/react-native-static-server#122]
I have a question, can we run multiple resources in one server with the resource structure as below. The document said `BEWARE: At most one server instance can be active within an app at the same time. Attempts to start a new server instance will result in the crash of that new instance.`
```
assets/
- app1/assets
- app2/assets
- app3/assets
```

**Comment by birdofpreyru** [comment]
I believe, Lighttpd provides such option; I haven't tried it myself, you should look into [Lighttpd docs](https://redmine.lighttpd.net/projects/lighttpd/wiki) how to configure it.
