### ISSUE TITLE
server crashes with mod_openssl

### ISSUE THREAD

**Issue by iamswain25** [birdofpreyru/react-native-static-server#124]
### context
I'm serving the webview from https and try to load mobile internal data through the static server.
However, ios webview safari does not allow http requests on https website.
I tried to add below extraConfig
```
extraConfig: `
            server.modules += ("mod_openssl")
            $SERVER["socket"] == ":3001" {
              ssl.engine = "enable"
              ssl.pemfile = "${fileDir}/resource/ssl/cert.pem"
              ssl.privkey = "${fileDir}/resource/ssl/key.pem"
            }
          `,
```
the app crashes
```
New state: "CRASHED".
Details: "Server exited with error".
```
is it possible to configure ssl onto the server?

### edit
@dr.pogodin/react-native-static-server/lighttpd1.4/src/plugin.c.142) mod_openssl plugin not found

**Comment by birdofpreyru** [comment]
Yes, it requires some library updates to include `mod_openssl` into the build.

**Comment by iamswain25** [comment]
### aftermath
I tried to manually add mod_openssl in `CMakeLists.txt` file but the app build failed. We decided to drop static server and instead upload internal file onto S3, then make backend consumes it. It's a lot of hassle injecting presigned url with additional parameters through `window.postMessage`. If anyone reading this thread thinking they can circumvent ios policy by tweaking info.plist reading document [NSAppTransportSecurity](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity), we failed miserably.
