### ISSUE TITLE
Airplane Mode results in errors

### ISSUE THREAD

**Issue by vyrotek** [birdofpreyru/react-native-static-server#2]
Hi. We've noticed that when devices are put in Airplane Mode that the webserver sometimes has issues. It seems unusual for it to be affected by the internet connection since we're serving only local files. Has anyone else experienced this?

**When "localOnly" is set to "true":**
Android works properly.
iOS shows a loading spinner and never loads the content.

**When "localOnly" is set to "False":**
 Android shows a white page when you switch to Airplane mode while the server is running. Restarting fixes it.
 iOS always shows this connection error page. Restarting does not fix it.

```
Error loading page
Domain: NSURLErrorDomain
Error Code: -1009
Description: The internet connection appears to be offline.
```

**Comment by birdofpreyru** [comment]
@vyrotek in my projects, so far, I only use it with `localOnly` equal **true**. I just rapidly checked whether Airplane mode breaks something in some project of mine on iOS, and it does not seem to be the case, the static server seems to work fine on iPad with iOS 15.5, Airplane mode, and `localOnly` **true**.

**Comment by vyrotek** [comment]
Thanks for checking! That's helpful to know. Must be something else in our stuff then.
