### ISSUE TITLE
[iOS/macOS] On M1 Mac machines CMake step of the library build fails to find CMake binary if Homebrew `bin` folder is not added to `PATH`

### ISSUE THREAD

**Issue by birdofpreyru** [birdofpreyru/react-native-static-server#29]
> Hi @asurare , I'll only agree this is an issue with this library, if you confirm the Xcode itself is able to locate cmake without having its location in PATH (I mean, in some other build / build step, probably it looks up its path from some other environment variable, set by SDK, or whatever? — in such case I can update the library's build process to check that variable for possible cmake location). Otherwise, I'd say the problem is that you don't have cmake or homebrew installed correctly, to automatically have it added to PATH, and you should fix it not in the library, but appending its location to PATH in the start-up `.bashrc` file (or whatever it is called on macOS).

`cmake` is indeed accessible in a classic bash session (both sh and zsh), and is exported to the path (found in its correct location through `which` → `/opt/homebrew/bin/cmake`). I'm not sure how Xcode try to resolve the path to find these binary files, but maybe this is where there is an issue (so maybe more Xcode related). I won't have time today to explore this, but I'll explore this asap and create an issue if necessary. (And btw, ty a lot for forking and maintaining this lib, that saved me a lot of work 😄)

_Originally posted by @asurare in https://github.com/birdofpreyru/react-native-static-server/issues/18#issuecomment-1490004440_

**Comment by birdofpreyru** [comment]
Ok, @asurare , let's move this discussion here. So, yeah, I definitely can correct the build script, to look for CMake via `which cmake` command, rather than just saying `cmake ...`; but it will be great if you play around with it first, and check whether it helps. Another thing I need you to confirm is, where actually it fails for you? Because there are two places I call for CMake during the library build step:
- [One is here](https://github.com/birdofpreyru/react-native-static-server/blob/a95b656bfd89b9ba8f83dec85429b2a147a8d52c/dr-pogodin-react-native-static-server.podspec#L45-L50) &mdash; the block of code it belongs to is emitted by XCode into a shell script, which is then called, and does the "top-level cmake build".
- [Another one is here](https://github.com/birdofpreyru/react-native-static-server/blob/a95b656bfd89b9ba8f83dec85429b2a147a8d52c/CMakeLists.txt#L66-L85) &mdash; this happens at the configuration step of the "top-level cmake build" &mdash; it spawns and waits for a child CMake build of PCRE2 dependency.

Does it fail to find CMake in the first or in the second place? What do you get in the log just before it says it can't find it?

**Comment by birdofpreyru** [comment]
So, folks, who have this issue with CMake path search, I've double-checked how it is all set up on my macOS system.

I have CMake installed via [Homebrew](https://brew.sh), so it lives in `/usr/local/Cellar/cmake`, and also Homebrew automatically created the symlink to it in `/usr/local/bin`. Apparently, `/usr/local/bin` is by default present in my `PATH`, and when I do `which cmake` in my console it locates it finds it as `/usr/local/bin/cmake`; and I have no issues with calling cmake command during the library build step.

I am not a deep expert in macOS / Linux / stuff, but the setup above looks quite standard to me, everybody is supposed to have, aside of some experts who require something different and exotic for some reason. Thus, I'll mark this issue as "_On Hold_" until somebody explains me why and what is different on his machine, causing the issue, and how it should be handled correctly; because in my current understanding, the current way it is handled in this library should work for everybody.

**Comment by birdofpreyru** [comment]
Hey @jacobira , have you tested it works for you if you substitute it in the library scripts in question? I kind of doubt it would be a fix, cause [the description of `which` command I googled](https://phoenixnap.com/kb/which-command-linux#:~:text=The%20which%20command%20allows%20users,file%20matching%20the%20given%20command.) says:

> _The `which` command allows users to search the list of paths in the `$PATH` environment variable and outputs the full path of the command specified as an argument. The command works by locating the executable file matching the given command._

This reads to me that if a console or script does not find a command because it is not in `$PATH`, the `which command` won't find it either. I'd guess, you system is just configured in such way that `/opt/homebrew/bin` is added to `$PATH` in console, where you try `which` command, but is not added to the `$PATH` of XCode environment used for the build. And most probably, the easiest fix on your side would be just to create that symlink from `/usr/local/bin/cmake` to `/opt/homebrew/bin/cmake`, like doing
```shell
sudo ln -s /opt/homebrew/bin/cmake /usr/local/bin/cmake
```

**Comment by birdofpreyru** [comment]
Thanks @ospfranco ! Yes, I still have Intel machine &mdash; Mac Mini 2020; and it seems to explain the issue, I googled now this article confirming what you say https://earthly.dev/blog/homebrew-on-m1. As time permits I'll look further how to fix it.

**Comment by birdofpreyru** [comment]
@ospfranco So, going through the article I mentioned in my previous message, I came across this:

> _Remember, Homebrew is now going to install packages in `/opt/homebrew/bin`. This new location is not part of your default `PATH`, so you’ll need to add it. The easiest way to do that is to follow the instructions Homebrew spits out after installation._
>
> _Add `eval "$(/opt/homebrew/bin/brew shellenv)"'` to your `.zshrc` or `.bashrc`. Now this command will run each time you start a new shell instance. It creates a series of environment variables, including `HOMEBREW_CELLAR="/opt/homebrew/Cellar"` and `HOMEBREW_REPOSITORY="/opt/homebrew"` and several others._
>
> _Most importantly, it adds `/opt/homebrew/bin` to your path: `export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";`._

Have you tried it? Does it solve the issue with finding cmake on M1 machines? If it does, I'd say no fix is needed in the library (because, it is then just a matter of correct Homebrew installation on M1), beside mentioning it in README for Mac use case.

**Comment by ospfranco** [comment]
Yeah you need to link it somehow but it is not your library's fault :)

**Comment by sadikyalcin** [comment]
Sorry to bump but I'm facing this exact issue @birdofpreyru. M1 Max & zsh. I used to be able to run via terminal using bash - hadn't tried xcode at that point. After switching to zsh, I haven't been able to run or do a build.

```
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

if [ -d "/opt/homebrew/opt/ruby/bin" ]; then
  export PATH=/opt/homebrew/opt/ruby/bin:$PATH
  export PATH=`gem environment gemdir`/bin:$PATH
fi

export PATH="/usr/local/mysql/bin:$PATH"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
export PATH="$(pyenv root)/shims:${PATH}"
export PYTHON=$HOME/.pyenv/versions/2.7.18/bin/python

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH="/usr/local/opt/ruby/bin:$PATH"

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"
```

Build fails with:

`Command PhaseScriptExecution failed with a nonzero exit code`

Logs show;

```
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/usr/local/share/cmake
CMake Error: Error executing cmake::LoadCache(). Aborting.

Command PhaseScriptExecution failed with a nonzero exit code
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/usr/local/share/cmake
CMake Error: Error executing cmake::LoadCache(). Aborting.
Command PhaseScriptExecution failed with a nonzero exit code
```

Cmake and pkg-config is installed. Symlinks created.

```
$ which cmake
/opt/homebrew/bin/cmake

$ which pkg-config
/opt/homebrew/bin/pkg-config

$ sudo ln -s $(which cmake) /usr/local/bin/cmake
ln: /usr/local/bin/cmake: File exists

$ sudo ln -s $(which pkg-config) /usr/local/bin/pkg-config
ln: /usr/local/bin/pkg-config: File exists
```

We're creating symlinks to ` /usr/local/bin/` but xcode log shows we're looking in `/usr/local/share/`?

**Comment by sadikyalcin** [comment]
Update: I've done 2 things and I've managed to get a build.

- Added symlinks to `/usr/local/share/`. I don't think this helped in any way tbh.
- Added Homebrew path to the `[CP-User] Build native dependencies` script (`eval "$(/opt/homebrew/bin/brew shellenv)"`)

**Comment by birdofpreyru** [comment]
I've double-checked this on my macOS machine. I have `eval "$(/opt/homebrew/bin/brew shellenv)"` in my `~/.zprofile`. I guess, that is a part of the correct Homebrew install (most probably, a manual step to do after the automatic part of the Homebrew install), and having it there allows to not add it into separate project scripts. Thus, not a problem with the library _per se_.

**Comment by Matthew-jeonghyeok** [comment]
I am experiencing the same issue as sadikyalcin. My CMake version is 3.31.4, and I have added eval "$(/opt/homebrew/bin/brew shellenv)" to both my .zshrc and .zprofile. When I add `eval "$(/opt/homebrew/bin/brew shellenv)"` to the [CP-User] native dependencies script, the Xcode build succeeds, but archiving fails. Are there any additional configurations I need to make? I have also previously tried `sudo ln -s /opt/homebrew/bin/cmake /usr/local/bin/cmake.`

**Comment by birdofpreyru** [comment]
:shrug: no, there is no additional config, I’d guess something got messed up in your project, and of try to cleanup the build folder, removing all artifacts from past builds, and doing a completely clean rebuild. If that doesn’t help, I’d try to build the example app from this repo, to narrow down whether it is a problem with your environment or with the particular project.

**Comment by Matthew-jeonghyeok** [comment]
I built the example and ran it on Xcode a few hours ago. However, the same issue occurs. It doesn’t seem to be a problem specific to my repository. I’m also using an M1.

**Comment by Matthew-jeonghyeok** [comment]
I apologize. There was an issue with my CMake version. I downgraded from 3.31.4 to 3.30.3 and successfully completed the build.
When installing CMake using Homebrew, it installs the most recent version. Therefore, I downloaded the DMG file from GitHub and completed the installation.

**Comment by sambouchard-newforma** [comment]
> Sorry to bump but I'm facing this exact issue [@birdofpreyru](https://github.com/birdofpreyru). M1 Max & zsh. I used to be able to run via terminal using bash - hadn't tried xcode at that point. After switching to zsh, I haven't been able to run or do a build.
> 
> ```
> # Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
> export PATH="$PATH:$HOME/.rvm/bin"
> 
> if [ -d "/opt/homebrew/opt/ruby/bin" ]; then
>   export PATH=/opt/homebrew/opt/ruby/bin:$PATH
>   export PATH=`gem environment gemdir`/bin:$PATH
> fi
> 
> export PATH="/usr/local/mysql/bin:$PATH"
> export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
> export PATH="$(pyenv root)/shims:${PATH}"
> export PYTHON=$HOME/.pyenv/versions/2.7.18/bin/python
> 
> export NVM_DIR="$HOME/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
> [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
> 
> export ANDROID_HOME=$HOME/Library/Android/sdk
> export PATH=$PATH:$ANDROID_HOME/emulator
> export PATH=$PATH:$ANDROID_HOME/platform-tools
> export PATH="/usr/local/opt/ruby/bin:$PATH"
> 
> # Set PATH, MANPATH, etc., for Homebrew.
> eval "$(/opt/homebrew/bin/brew shellenv)"
> ```
> 
> Build fails with:
> 
> `Command PhaseScriptExecution failed with a nonzero exit code`
> 
> Logs show;
> 
> ```
> CMake Error: Could not find CMAKE_ROOT !!!
> CMake has most likely not been installed correctly.
> Modules directory not found in
> /usr/local/share/cmake
> CMake Error: Error executing cmake::LoadCache(). Aborting.
> 
> Command PhaseScriptExecution failed with a nonzero exit code
> CMake Error: Could not find CMAKE_ROOT !!!
> CMake has most likely not been installed correctly.
> Modules directory not found in
> /usr/local/share/cmake
> CMake Error: Error executing cmake::LoadCache(). Aborting.
> Command PhaseScriptExecution failed with a nonzero exit code
> ```
> 
> Cmake and pkg-config is installed. Symlinks created.
> 
> ```
> $ which cmake
> /opt/homebrew/bin/cmake
> 
> $ which pkg-config
> /opt/homebrew/bin/pkg-config
> 
> $ sudo ln -s $(which cmake) /usr/local/bin/cmake
> ln: /usr/local/bin/cmake: File exists
> 
> $ sudo ln -s $(which pkg-config) /usr/local/bin/pkg-config
> ln: /usr/local/bin/pkg-config: File exists
> ```
> 
> We're creating symlinks to ` /usr/local/bin/` but xcode log shows we're looking in `/usr/local/share/`?

Ive managed to work around this error by creating an extra symlink, please see this issue comment : https://github.com/birdofpreyru/react-native-static-server/issues/130#issuecomment-2622129061
