### ISSUE TITLE
build release not working 

### ISSUE THREAD

**Issue by thanhnvpk01168** [birdofpreyru/react-native-static-server#3]
Everything works fine in debug, but after i build release it doesn't work

Enviroments:
"react": "18.0.0"
"react-native": "0.69.1"
"react-native-static-server": "https://github.com/birdofpreyru/react-native-static-server.git"
Testing on android 11

**Comment by thanhnvpk01168** [comment]
Hi @birdofpreyru , I think it's conflicting with this @react-native-community/netinfo package.
After removing it it works normally.
I do not know why

**Comment by nautikk** [comment]
@thanhnvpk01168 Hi, any idea fix this im using both

**Comment by birdofpreyru** [comment]
Hey @nautikk , but have you really encountered issues with this? In my projects I currently use this lib, **@dr.pogodin/react-native-static-server@0.6.0-alpha.7**, alongside **react-native-community/netinfo@9.3.6** and **react-native@0.70.4**, and have no issues. Neither had it with before with previous versions.

**Comment by nautikk** [comment]
Hi @birdofpreyru, no luck with upgrade rn and no error, in debug its works fine no idea what's going on. 
`this._staticServer = new StaticServer(
      8008,
      storageHelper.getDocumentDir(),
      {
        localOnly: true,
        keepAlive: false,
      },
    );

    this._staticServer.start().then(url => {
      this.setState({staticServerUrl: url});
    });`

**Comment by birdofpreyru** [comment]
@nautikk Are you doing it on Android? There if something works in Debug build, and mistereously does not work in Release, it might be due to Proguard wiping out some Java code in Release build. Try if the Release works with `minifyEnabled false` option in your **build.gradle**.

Other thing, what is `this` in your code? It kind of looks like you are creating and starting a new instance of static server on each re-render of `this` component - that isn't good.

**Comment by nautikk** [comment]
@birdofpreyru Yes, only android release not working, ill try minifyEnabled: False

this is my component

` componentDidMount() {
    this._isMounted = true;
    Orientation.lockToLandscape();
    StatusBar.setHidden(true);
    this._staticServer = new StaticServer(
      8008,
      storageHelper.getDocumentDir(),
      {
        localOnly: true,
        keepAlive: false,
      },
    );
    this._staticServer.start().then(url => {
      this.setState({staticServerUrl: url});
    });
    this.fetchData({
      titleUid: this.props.route.params.titleUid,
      episodeUid: this.props.route.params.episodeUid,
    });
  }`

**Comment by nautikk** [comment]
@birdofpreyru No luck, thanks your resposne.
