### ISSUE TITLE
[Android] The build for RN Old Architecture was broken by v0.7.8

### ISSUE THREAD

**Issue by charlyschulte** [birdofpreyru/react-native-static-server#32]
i updated the react-native-static-server library to 7.9 and now i cant build on android. i get the error message:
ReactNativeStaticServerModule is not abstract and does not override abstract method start(double,String,Promise) in ReactNativeStaticServerSpec
public class ReactNativeStaticServerModule

do you have any clue, what the problem might be?

**Comment by birdofpreyru** [comment]
Ogh... sorry about, it turns out in **v0.7.8** I missed a small change needed in the native Android / Old Architecture code, which broke support of Old Achitecture on Android.

This:
https://github.com/birdofpreyru/react-native-static-server/blob/11f8944f3ba3dc70d49017fedbbdb7a4ebbe08cd/android/src/oldarch/ReactNativeStaticServerSpec.java#L21
should read:
```java
public abstract void start(double id, String configPath, String errlogPath, Promise promise); 
```

Will fix in the next release.

**Comment by frederiko-famobi** [comment]
Hello there, same error here while trying to build:

```
> Task :app:processDebugManifest
> Task :app:processDebugManifestForPackage
> Task :dr.pogodin_react-native-static-server:compileDebugJavaWithJavac
[stderr] 
/home/expo/workingdir/build/node_modules/@dr.pogodin/react-native-static-server/android/src/main/java/com/drpogodin/reactnativestaticserver/ReactNativeStaticServerModule.java:27: error: ReactNativeStaticServerModule is not abstract and does not override abstract method start(double,String,Promise) in ReactNativeStaticServerSpec
[stderr] 
public class ReactNativeStaticServerModule
[stderr] 
       ^
[stderr] 
1 error
> Task :dr.pogodin_react-native-static-server:compileDebugJavaWithJavac FAILED
```

I see that is marked as ready. Is there any news about the next update with the fixes?

Thank you!

**Comment by birdofpreyru** [comment]
@frederiko-famobi probably I'll release later today, or within the next few days. I wanna complete and include into the same release the clean-up I do for #28, just to avoid doing a separate release for each one-liner fix.
