### ISSUE TITLE
pcre2.h not found

### ISSUE THREAD

**Issue by ospfranco** [birdofpreyru/react-native-static-server#40]
Hi!

Thanks a lot for the package. When I installed the package a week ago everything worked perfectly the first time. I just tried onboarding a new team member and I got the following error on her machine:

<img width="1280" alt="CleanShot 2023-05-17 at 15 23 28" src="https://github.com/birdofpreyru/react-native-static-server/assets/1634213/38e98590-266f-4d65-8178-f780fcc5d6df">

I've fumbled around with env variables, brew env, clearing all possible caches (derived data, ios/build, pods) multiple times and nothing seemed to work.

I finally came back to my machine and did a complete clean (derived data, node_modules, pods) and now I'm facing the same issue. No matter what I try to clear and how I re-install the dependencies I face the same issue. [The full log output](https://pastebin.com/XeQujDLX).

I'm running this on:
macOS Ventura 13.3.1(a)
RN 0.71.8
"@dr.pogodin/react-native-static-server": "^0.7.10"

Any idea how to fix the issue?

**Comment by ospfranco** [comment]
I tried the workaround suggested in [this comment](https://github.com/birdofpreyru/react-native-static-server/issues/18#issuecomment-1441539390) but to no avail. `pcre2.h` is still not found.

**Comment by ospfranco** [comment]
what's baffling to me, is that on the first time I installed the package everything was working fine, it's only after I cleared the caches that I got this error...

**Comment by ospfranco** [comment]
When building from the command line I don't "seem" to have the same issue, but compilation still fails:

```
▸ Building library liblighttpd.a
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'ZERO_CHECK' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_sockproxy' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_rrdtool' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_proxy' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_wstunnel' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_userdir' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_webdav' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_status' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_ssi' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_extforward' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_dirlisting' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_deflate' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_cgi' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_authn_file' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_auth' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_ajp13' from project 'rn-static-server')
    ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no active architecture could be computed; building for all applicable architectures (in target 'mod_accesslog' from project 'rn-static-server')
▸ Build Succeeded
▸ Running script 'Copy generated compatibility header'
▸ Running script '[CP-User] Generate Specs'
▸ Building library libRNSentry.a
▸ Compiling FBReactNativeSpec-generated.mm
▸ Compiling RCTVibration.mm
▸ Compiling RCTLinkingManager.mm
▸ Compiling RCTNativeAnimatedModule.mm
▸ Compiling RCTNetworking.mm
▸ Compiling RCTSettingsManager.mm
▸ Compiling RCTImageEditingManager.mm
▸ Compiling RCTBlobManager.mm
▸ Compiling RCTAccessibilityManager.mm
▸ Compiling RCTImageLoader.mm
▸ Compiling RCTImageStoreManager.mm
▸ Compiling RCTFileReaderModule.mm
▸ Compiling RCTNativeAnimatedTurboModule.mm
▸ Compiling RCTDeviceInfo.mm
▸ Compiling RCTAlertManager.mm
▸ Compiling RCTDevLoadingView.mm
▸ Compiling RCTClipboard.mm
▸ Compiling RCTAppState.mm
▸ Compiling RCTAppearance.mm
▸ Compiling RCTWebSocketModule.mm
▸ Building library libReact-Codegen.a
▸ Compiling RCTTiming.mm
▸ Compiling RCTStatusBarManager.mm
▸ Compiling RCTSourceCode.mm
▸ Compiling RCTRedBox.mm
▸ Compiling RCTPlatform.mm
▸ Compiling RCTLogBox.mm
▸ Compiling RCTKeyboardObserver.mm
▸ Compiling RCTI18nManager.mm
▸ Compiling RCTExceptionsManager.mm
▸ Compiling RCTDevSplitBundleLoader.mm
▸ Compiling RCTDevSettings.mm
▸ Compiling RCTDevMenu.mm
▸ Compiling RCTActionSheetManager.mm
▸ Building library libReact-RCTVibration.a
▸ Building library libReact-RCTSettings.a
▸ Building library libReact-RCTNetwork.a
▸ Building library libReact-RCTLinking.a
▸ Building library libReact-RCTAnimation.a
▸ Building library libReact-RCTImage.a
▸ Building library libReact-RCTBlob.a
▸ Running script 'Copy generated compatibility header'
▸ Building library libReact-CoreModules.a
▸ Compiling Server.mm
▸ Compiling Errors.mm
▸ Compiling dr-pogodin-react-native-static-server-dummy.m
▸ Compiling ReactNativeStaticServer.mm
▸ Building library libdr-pogodin-react-native-static-server.a
▸ Running script '[CP] Check Pods Manifest.lock'
▸ Running script 'Start Packager'
m▸ Copying /Users/osp/Library/Developer/Xcode/DerivedData/abl_config_app-fyandjlpgbiuzaacfxqzrzvoczbs/Build/Products/Debug-iphonesimulator/abl_config_app.app/update-eM4-2.0.yar
▸ Copying /Users/osp/Library/Developer/Xcode/DerivedData/abl_config_app-fyandjlpgbiuzaacfxqzrzvoczbs/Build/Products/Debug-iphonesimulator/abl_config_app.app/UniversLTPro_roman.otf
▸ Copying /Users/osp/Library/Developer/Xcode/DerivedData/abl_config_app-fyandjlpgbiuzaacfxqzrzvoczbs/Build/Products/Debug-iphonesimulator/abl_config_app.app/UniversLTPro_light.otf
▸ Copying /Users/osp/Library/Developer/Xcode/DerivedData/abl_config_app-fyandjlpgbiuzaacfxqzrzvoczbs/Build/Products/Debug-iphonesimulator/abl_config_app.app/1_8_0.bin
▸ Copying /Users/osp/Library/Developer/Xcode/DerivedData/abl_config_app-fyandjlpgbiuzaacfxqzrzvoczbs/Build/Products/Debug-iphonesimulator/abl_config_app.app/UniversLTPro_bold.otf
▸ Copying InfoPlist.strings
▸ Copying InfoPlist.strings
▸ Copying InfoPlist.strings
▸ Compiling BootSplash.storyboard

❌  fatal error: module 'yoga' in AST file '/Users/osp/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/XDG1T5UWE6UY/yoga-1934T5M7PQHY6.pcm' (imported by AST file '/Users/osp/Library/Developer/Xcode/DerivedData/abl_config_app-fyandjlpgbiuzaacfxqzrzvoczbs/Build/Intermediates.noindex/PrecompiledHeaders/abl_config_app-Bridging-Header-swift_2P6MDJO1IMXP8-clang_XDG1T5UWE6UY.pch') is not defined in any loaded module map file; maybe you need to load '/Users/osp/Developer/abl/ios/Pods/Headers/Public/yoga/Yoga.modulemap'?


▸ Processing Info.plist
▸ Compiling main.m
▸ Compiling abl_config_app_vers.c
▸ Compiling AppDelegate.mm
▸ Compiling ABLNative.m

⚠️  /Users/osp/Developer/abl/ios/ABLNative.m:4:12: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]

@interface RCT_EXTERN_MODULE(ABLNative, NSObject)
              ~~~~~~~~~~~~~                        ~~~~~~~^~~~~~~


▸ Linking abl_config_app

❌  ld: library not found for -lPods-abl_config_app



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ospfranco** [comment]
Funny, after running build on the command line and trying again on xcode it seems like the dependency is correctly compiled but libPods still fails... so maybe it is really an issue of the environment on xcode

![CleanShot 2023-05-17 at 18 21 57](https://github.com/birdofpreyru/react-native-static-server/assets/1634213/115a1706-46b4-4bae-a926-646c2e3fb3c5)

**Comment by birdofpreyru** [comment]
Hey @ospfranco , I don't have time to look into it carefully right now, though... the CMakeLists block that complains about not finding pcre2.h is this one: https://github.com/birdofpreyru/lighttpd1.4/blob/b50cd3698147d5d1d8a86fd4e5c934355d08d2f5/src/CMakeLists.txt#L534-L582. So, you may just add there some `message()` instrunctions, run the build a few times, and thus figure out what branch of the configuration it follows on your system and at what goes wrong with finding the header.

**Comment by ospfranco** [comment]
Thanks @birdofpreyru, yeah I figured that block some hours ago, but cmake is a bit of chinese to me. From a first look everything looks "correct" it tries to find `pcre2.h` via `find_path` command... and the line that bails out is quite clear:

https://github.com/birdofpreyru/lighttpd1.4/blob/b50cd3698147d5d1d8a86fd4e5c934355d08d2f5/src/CMakeLists.txt#L578

But no idea why it reaches that point. I will continue to try to debug this. Thanks for the reply!

**Comment by marnowicki** [comment]
Based on https://github.com/birdofpreyru/react-native-static-server/issues/23#issuecomment-1466554136 add `-DWITH_PCRE2=OFF` to `EXTRA_CONFIG_ARGS` in node_modules/@dr.pogodin/react-native-static-server/dr-pogodin-react-native-static-server.podspec like this: 
`EXTRA_CONFIG_ARGS="-DCMAKE_OSX_DEPLOYMENT_TARGET=${IPHONEOS_DEPLOYMENT_TARGET} -DCMAKE_SYSTEM_NAME=iOS -GXcode -DWITH_PCRE2=OFF"` 
and do `pod install` again.

**Comment by birdofpreyru** [comment]
Well @marnowicki , if everybody works around the issue, we'll never figure out the root cause nor fix it :)

**Comment by ospfranco** [comment]
Continuing my investigation.

After taking a closer look into lighthttpd CMakeLists this was the first line that failed:

```
pkg_check_modules(PCRE2 libpcre2-8)
```

Some googling shown that pkg_check_modules is considered harmful, but most importantly it is a hard dependency on `pkg-config` which is installed on my machine by brew but not linked because M1. So I created a symbolic link for it (same as cmake)

```
sudo ln -s $(which pkg-config) /usr/local/bin/pkg-config
```

This in theory allows Xcode to successfully find pcre2. However, it now always throws the error that libPods.a is not found/not generated without any output. Could it be because lighthttp is spawned/compiled in it's own worker thread/process?

<img width="1272" alt="CleanShot 2023-05-18 at 08 05 25" src="https://github.com/birdofpreyru/react-native-static-server/assets/1634213/549533bc-49c1-4ae3-8080-b798ccff5a4b">

**Comment by ospfranco** [comment]
At least it looks to me that the compilation process is not waiting for the worker thread to finish and it just tries to compile the app even though static-server.a is not ready

<img width="903" alt="CleanShot 2023-05-18 at 08 09 09" src="https://github.com/birdofpreyru/react-native-static-server/assets/1634213/b09cf354-f926-4eeb-8d8d-3d89cde362a2">

**Comment by ospfranco** [comment]
Ok, so after fumbling around with architectures, I got a different set of linker errors with missing x86_64 symbols on PCRE2. I did not manage to solve this issue, but once I tried building for the real device it finally worked. So I guess this library cannot compiled? or at least on my project there is a hard requirement for Rosetta since some of the libraries I'm using are not arm64 compatible with the simulator.

**Comment by birdofpreyru** [comment]
Hey @ospfranco , thanks for continuing with the troubleshooting, this is very helpful! The architectures issue I'll try to fix in the next release &mdash; it sounds like some CMake arguments / configuration should be added to PCRE2 configuration / compilation to force its build for multiple architectures, including x86_64, on macOS. Otherwise the build selects target architectures automatically, based on the other settings, and it sounds it selects it wrong. I actually was fixing something like this before already, but probably missed x86_64 or PCRE2 case. And what you figured out about linking of `cmake` and `pkg-config` on M1 machines &mdash; this I'll add to the library README.

**Comment by birdofpreyru** [comment]
@ospfranco if you get to this faster than I do, can you try modifying this block: https://github.com/birdofpreyru/react-native-static-server/blob/458348a3e3345542a6092b83654dc1f7a9094248/dr-pogodin-react-native-static-server.podspec#L35-L43C9 , adding `-DCMAKE_OSX_ARCHITECTURES=arm64;x86_64`, currently present at line 42, also into args on line 37? Then do pod update in your host project, and re-build.

**Comment by ospfranco** [comment]
Today is a holiday, I actually took some time to figure this out because I found the problem interesting, but I can try it tomorrow! thanks for replying though!

**Comment by birdofpreyru** [comment]
> _Today is a holiday_

Wow! Not in Spain :sweat_smile: It is actually surprising to me &mdash; I looked in your profile you are based in Germany, and if I got it right the holiday is the Ascension Day? I can't believe there is a Christian feast which is bank holiday in Germany, but not in Spain :rofl:

**Comment by ospfranco** [comment]
yeah :) europe is weird

On another note, I find it super confusing why it worked the first time I installed the package but not on subsequent builds... pkg-config was not linked at the time and the app compiled just fine.

**Comment by birdofpreyru** [comment]
@ospfranco Probably [v0.7.11](https://github.com/birdofpreyru/react-native-static-server/releases/tag/v0.7.11) fixes it, at least for me it now builds PCRE2 for both arm64 and x86_64 archs when building for the iPhone simulator.

**Comment by ospfranco** [comment]
Seems to be working! great! As another point, the outputs should be specified, because right now lighttpd is being compiled every time the app is compiled.

Thanks a lot for patching it!

**Comment by birdofpreyru** [comment]
Cool! Yeah, outputs should be specified, I'll probably do it in the next release. Will track that separately as #41.

**Comment by dagouzhi** [comment]
`https://gist.github.com/anilcancakir/29b4b6b5925b3fc7108a7fc4e329d322 `
It works for me

**Comment by ospfranco** [comment]
@dagouzhi Local installation is never really the best idea :) 

Having the sources in the repo and compiling them makes sure the correct version and architecture will always work. The latest version is working for me without issues. Though having to link cmake and pkg-config is less than ideal, it's a compromise.
