### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by wjm777** [birdofpreyru/react-native-static-server#45]
The plug-in prompts that the dependency cannot be established in the Android build

![image](https://github.com/birdofpreyru/react-native-static-server/assets/101913530/bd7120cc-975e-43e8-8ad6-70907b78036b)

Package JSON 

"dependencies": {
    "@dr.pogodin/react-native-static-server": "^0.7.11",
    "react": "18.2.0",
    "react-native": "0.71.4",
    "react-native-fs": "^2.20.0",
  },

**Comment by birdofpreyru** [comment]
Hey @wjm777 , I am pretty sure it is some issue / glitch on your side, not a problem with this library &mdash; I've last was building with it for Android yesterday, both the example app, and a real project; had no issues with dependencies.
