### ISSUE TITLE
exception in native call from js error

### ISSUE THREAD

**Issue by b3rkaydem1r** [birdofpreyru/react-native-static-server#5]
![image](https://user-images.githubusercontent.com/35340093/179250681-6b0ec75c-44db-4935-af00-5e01e77cce52.png)
![image](https://user-images.githubusercontent.com/35340093/179250745-d01a1106-4e63-4c88-aac4-156143666869.png)

**Comment by b3rkaydem1r** [comment]
React Native: 0.68.2

**Comment by 7772** [comment]
@b3rkaydem1r

I got the idea to solve this issue thanks to your question.
I saw [android codes](https://github.com/birdofpreyru/react-native-static-server/blob/4f4942573cd0b7653dbf0d4f8b21b9c61de503f9/android/src/main/java/com/futurepress/staticserver/FPStaticServerModuleImpl.java#L90) and finally noticed working code.

You just run server with root path then you don't need to modify android code.

```
let server = new StaticServer(8080, '/storage/emulated/0');
```
