### ISSUE TITLE
Approaches to best load local HTML

### ISSUE THREAD

**Issue by qwertynik** [birdofpreyru/react-native-static-server#53]
What are the best practices to load and view HTML stored locally on the device? Attempted to find suggestions in the README.md but could not find any.

Usually when building PWA's caching static resources and serving them is relatively straightforward. window.cache, works pretty well. No server management, or other maintenance required. Of course, there are space limitations imposed on PWA apps. Are there any such best practices/internal features that can be used when rendering locally stored HTML in a WebView?

This is not an issue as such. But since discussion is not available, using issues.

**Comment by birdofpreyru** [comment]
Hmm... doesn't this work for you? https://github.com/birdofpreyru/react-native-static-server/tree/master#bundling-in-server-assets-into-an-app-statically Or are you looking for something different?

**Comment by qwertynik** [comment]
This worked. (except for videos not loading - this could be a react-native-webview package issue)

However, not all assets can be bundled directly into the app and they will need to be served from the local storage. For those cases, wanted to know the best way to do it.

**Comment by birdofpreyru** [comment]
> _However, not all assets can be bundled directly into the app and they will need to be served from the local storage. For those cases, wanted to know the best way to do it._

Yeah, I guess, you just do what you wrote: download them to some local location from where you can serve them with this library. I haven't tried something like this myself, thus I have nothing to add, beside that this looks perfectly doable to me.

**Comment by qwertynik** [comment]
Ok. Will attempt this approach.
