### ISSUE TITLE
Access Denied error shown before page loads local HTML

### ISSUE THREAD

**Issue by qwertynik** [birdofpreyru/react-native-static-server#54]
Before the local HTML is loaded, the below error is shown for a few seconds:

![image](https://github.com/birdofpreyru/react-native-static-server/assets/6836536/5e3a371f-d670-48b1-becd-e8722f1c30a5)

Doesn't look usual. Any ideas what could be wrong and how to resolve it?

**Comment by birdofpreyru** [comment]
Seems like you are access the resource before it is ready to be accessed.

**Comment by qwertynik** [comment]
🎯
