### ISSUE TITLE
Increasing the reach of this package and saving developers time

### ISSUE THREAD

**Issue by qwertynik** [birdofpreyru/react-native-static-server#55]
Running a static server on a mobile app isn't a fringe use-case. Therefore, having a solid package to accomplish the same is essential. From my experience with this package so far, this does have the potential to be the package that allows adding static servers to apps. However, [react-native-webview](https://github.com/react-native-webview/react-native-webview/) currently links to a non-working package (or perhaps difficult to setup). To save developers from wasting their time searching for a working package and to increase the reach and perhaps the quality of this package - with more community contribution, created this [PR](https://github.com/react-native-webview/react-native-webview/pull/3049). Upvoting in the PR should lead to a better experience.

**Comment by birdofpreyru** [comment]
Cool! A huge thanks @qwertynik !

**Comment by qwertynik** [comment]
No problem. You deserve much bigger thanks for forking the repo, resolving issues, and creating this package🏗

**Comment by birdofpreyru** [comment]
Closing, as it does not imply any clear further actions for the library.

**Comment by qwertynik** [comment]
@birdofpreyru This is now a part of the react-native-webview documentation 👍. Hopefully, developers searching for ways to run servers on their apps, have it easier.
