### ISSUE TITLE
Library may break if JS layer is reloaded by RN while the server is active

### ISSUE THREAD

**Issue by dagouzhi** [birdofpreyru/react-native-static-server#56]
If you call `codePush.restartapp();` An error occurs when `server.start()` is called

> `another server instance is active`

`react-native-code-push@8.0.2`
`@dr.pogodin/react-native-static-server@0.8.0`

**Comment by birdofpreyru** [comment]
Hey @dagouzhi , technically what happens here, I believe, `codePush.restartapp()` reloads JS layer of the library, it does not stop the actual server in the Native layer, thus the error when reloaded JS layer attempts to start a fresh server, without killing the old one first.

A quick workaround for you &mdash; be sure to call `server.stop()` prior to the restart.

A proper fix will be to hook it up to automatically kill the server in native layer when such reload of JS happens. At the moment, I am not sure whether it can be done in JS layer (which would be perfect), I think I know how to do within the native layer on Android, but then not sure how to do it in the native layer for other platforms. Thus, one way or another, I'll need some time to investigate and fix it. On what platform have you encountered this problem?

**Comment by dagouzhi** [comment]
@birdofpreyru I could try to do this, but hopefully it would be better to have a static method that kills all services, or to call the start method with a configuration that forces it to start, even if there were previously active services

**Comment by birdofpreyru** [comment]
> _but hopefully it would be better to have a static method that kills all services, or to call the start method with a configuration that forces it to start, even if there were previously active services_

It will work great for your scenario, but I am afraid in other scenarios it will open doors to hard-to-triage bugs. So, the best permanent solution is just to figure out all situations when the current server should be killed automatically, and do just it.

**Comment by birdofpreyru** [comment]
Let’s keep it open, I need it as a reminder to look into it.

**Comment by Quangdm-cdm** [comment]
@birdofpreyru hi. I still facing this issue. Can you re-check and give me some solution? Thank you so muchh :((

**Comment by birdofpreyru** [comment]
@Quangdm-cdm will you elaborate, please, what exactly do you do when encountering this issue? Are you stopping the server before the JS layer reload?

**Comment by Quangdm-cdm** [comment]
> @Quangdm-cdm will you elaborate, please, what exactly do you do when encountering this issue? Are you stopping the server before the JS layer reload?

Yes i do, i also log server state before start server and result is INACTIVE. But it still show error another server instance is active

**Comment by birdofpreyru** [comment]
@Quangdm-cdm try to log the result of [await **getActiveServerId()**](https://github.com/birdofpreyru/react-native-static-server?tab=readme-ov-file#getactiveserverid) &mdash; that's the only method in the library that actually makes an async call to the native side to check whether there is an active server or not; alternative ways to get server state just return the state recorded on JS side, which may be set to INACTIVE as soon as a request to stop is sent to the native side, but without waiting the request is actually fulfilled; and if you reset the JS layer entirely, then JS side just assumes there is no active server on the native side.

Do you wait for `stop()` promise to resolve?
