### ISSUE TITLE
Current implementation requires `@babel/plugin-proposal-private-methods` plugin in RN Babel config, to be added to README

### ISSUE THREAD

**Issue by b3rkaydem1r** [birdofpreyru/react-native-static-server#6]
It is fixing when i add 
`@babel/plugin-proposal-private-methods`
to babel file. But then i am getting an error for Flatlist.
![hata](https://user-images.githubusercontent.com/35340093/179419325-dacffaa4-b92e-4a93-bd6c-23acc60bb5a3.png)

**Comment by birdofpreyru** [comment]
Ogh... try to configure it as `['@babel/plugin-proposal-private-methods', {loose: true}],`? It turns out I have it in all my RN projects I use this library with, thus haven't realize it is a problem for default babel config.

**Comment by b3rkaydem1r** [comment]
Thanks. Working now.

**Comment by thanhnvpk01168** [comment]
Hi @birdofpreyru  @b3rkaydem1r .
I still do not understand.
how did you fix it?

**Comment by thanhnvpk01168** [comment]
<img width="748" alt="Screen Shot 2022-07-22 at 9 57 27 PM" src="https://user-images.githubusercontent.com/58645779/180466722-6e53fd83-baa7-4ff4-90c1-9b5580dad960.png">

**Comment by birdofpreyru** [comment]
@thanhnvpk01168 didn't it help to add the plugin, like you show in your screenshot?

**Comment by thanhnvpk01168** [comment]
@birdofpreyru 
oh, so do you have any way to fix this?

**Comment by birdofpreyru** [comment]
I'm not following, what do you mean? Fixing it in the library to not have adding the plugin to the host project? I guess can be done.

**Comment by b3rkaydem1r** [comment]
@thanhnvpk01168 It was working when i add. But a few days later it's started not working. Same error. I am deleting the @babel/plugin-proposal-private-methods line but error is same. It doesnt work with flatlist.

**Comment by b3rkaydem1r** [comment]
is it possible to disable @babel/plugin-proposal-private-methods library? @birdofpreyru

**Comment by birdofpreyru** [comment]
I don't know. I was under impression it is still necessary to make private JS class members to work in RN. It makes no sense to get rid of private members in code, but maybe it can work already without this plugin. Needs investigation.

**Comment by b3rkaydem1r** [comment]
Can you check? I'm stuck at this point.

**Comment by birdofpreyru** [comment]
It is of very low priority for me. It works as is in my projects where I use the library. Also, in my understanding, the root problem is a bug in React Native or in the Babel plugin, as there is nothing wrong with using private class methods in the library.

**Comment by b3rkaydem1r** [comment]
You can use SectionList from react native. @thanhnvpk01168

**Comment by bachlongkocanh** [comment]
> You can use SectionList from react native. @thanhnvpk01168

I had been try it, but still error

**Comment by b3rkaydem1r** [comment]
Its have cache problem. Create new project then try on it.

**Comment by birdofpreyru** [comment]
Hey, looking at @thanhnvpk01168's screenshot of Babel config above, I just now noticed that it is missing to also include
```json
"presets": ["module:metro-react-native-babel-preset"]
```
without that line, Babel would only use a few plugins mentioned in the babel config, and would not apply the rest of Babel plugins RN relies on. Can it be the root problem you having to make the private methods work for you?

**Comment by birdofpreyru** [comment]
FYI: After yet another complaint about it (#9) I surrendered, and just released **v0.6.0-alpha.4** which gets rid of the private class features for now.
