### ISSUE TITLE
Measures to be taken for keeping the server available for longer durations

### ISSUE THREAD

**Issue by qwertynik** [birdofpreyru/react-native-static-server#64]
From the codebase, API ref did not find anything that stops the server after a certain period of inactivity. However, not certain how long the server can remain idle and be usable. Are there any recommendations that can be implemented to make the server available for longer durations?

**Comment by birdofpreyru** [comment]
As you said &mdash; I believe, there is nothing stopping the server after a certain period of inactivity.
