### ISSUE TITLE
TypeScript error: Exporting local "EncodingT", which is not declared

### ISSUE THREAD

**Issue by Braden1996** [birdofpreyru/react-native-static-server#68]
Hello!

I'm trying to setup this library on a Expo pre-build project. However, when importing the library I am seeing the following TypeScript error. Not to sure where to even start debugging this? Is there any information I could provide to help?

![CleanShot 2023-09-13 at 15 13 34](https://github.com/birdofpreyru/react-native-static-server/assets/5165963/44906a85-c406-4bb5-bc2e-e92311c75a38)

**Comment by birdofpreyru** [comment]
Hey @Braden1996 , this complain is about [my fork of RNFS library](https://github.com/birdofpreyru/react-native-fs), not sure why it happens though... it could be a mistake there, but checking the latest code in the repo, that [**type EncondingT** export at the line 530](https://github.com/birdofpreyru/react-native-fs/blob/b8c3d92d427fd948326362434111b698ebae1025/src/index.ts#L530) exports the type [imported at the line 21](https://github.com/birdofpreyru/react-native-fs/blob/b8c3d92d427fd948326362434111b698ebae1025/src/index.ts#L21). Can you just play with that code in your `node_modules` version of the package, and thus figure out why it does not work for you, and what should be corrected. Perhaps, it stuck with an older version of RNFS where was some mistake?
