### ISSUE TITLE
Improve documentation for assets bundling for iOS, and `resolveAssetsPath()`

### ISSUE THREAD

**Issue by belyylis** [birdofpreyru/react-native-static-server#70]
Hi all! I created a game folder in the assets folder in the root of the project.
I did everything as in the instructions, but it gives me a 404 error. I tried to build an example, but got an error. I copied the code from App.tsx, but I still get 404. It is clear that the server is running, could you give more precise instructions on how to find the file? Checked on iOS. Added files to Xcode.

**Comment by belyylis** [comment]
I found an indication of where the files were sent, it is not the same as when calling resolveAssetsPath

**Comment by belyylis** [comment]
I add the folder name to the method ('games'). The path in the console is correct ...NAME.app/games. But in fact index.html lies a level higher. In ...NAME.app

**Comment by belyylis** [comment]
<img width="293" alt="image" src="https://github.com/birdofpreyru/react-native-static-server/assets/58907138/d6d39354-df48-4b13-aa00-23ff375c30c4">

Apparently I understood something wrong, there was the first option. Everything worked, but only in dev mode.
Now Xcode won't build. And on Android there is a white screen.
The dev works everywhere.

**Comment by birdofpreyru** [comment]
> _I add the folder name to the method ('games'). The path in the console is correct ...NAME.app/games. But in fact index.html lies a level higher. In ...NAME.app_

Ok, I have to re-check what is written in README once I have Mac machine around. In the example app, and the README is supposed to describe the same, test assets are kept inside `/assets/webroot` folder of the codebase, and I am not sure now, when adding it into Xcode project whether I was selecting the `webroot` folder itself, as README says, or maybe the parent `assets` folder. Anyway, the way I did it was to land the assets into `...NAME.app/webroot`, so when it is served by the server, it does not expose anything else beside the assets (as in your case it would expose everything inside app bundle).

I am not sure now, but probably I selected _Create groups_, and did not opt to copy files. Anyway, if it works for you in dev mode, but not in the release mode... my first guess would be there is some other problem, not related to the static server setup.

**Comment by birdofpreyru** [comment]
Ok, I did my best to improve instructions for static assets bundling into iOS apps. In general, as it was described before was correct. I checked that _Create folder references_ is the correct option for _Added folders_ switch. I'll close this issue now, but feel free to re-open, or create a new one, if you still have troubles with it.
