### ISSUE TITLE
Support to override http calls 

### ISSUE THREAD

**Issue by 1-AlenToma** [birdofpreyru/react-native-static-server#82]
After too much work I was able to make this work in all three platforms.

Now I got an issue or more a requirment

I am able to execute all html files i have in the assets folder but now I need the webview to make calls and get files on the user mobile.

So the WebView will say get me file X which it is not in the  assets folder but on the user mobile.

I do not want to make a copy for the user files to the assets and though that it would have been great if the library could let me  validate the get request and instead of getting the file from the assets, I would instead provide the file by manually reading it from the user mobile and send it to the web browser.

What do you think? is this a good Idea ? am I able to make this without changing the native code and just js files?

**Comment by birdofpreyru** [comment]
> _After too much work I was able to make this work in all three platforms._

Noob! It should not take much efforts at all ¯\\\_(ツ)\_/¯

> _What do you think? is this a good Idea? ..._

I think, it has little to do with this library, and I already told you, I have little interest to do free work or engineering advising for your project.
