### ISSUE TITLE
[README][Android]: Mention "Cleartext Traffic" configuration in the "Getting Started" section

### ISSUE THREAD

**Issue by shahinyan11** [birdofpreyru/react-native-static-server#86]
The local assets work for debug mode. But in release mod it returns error - net::ERRCLEARETEXT_NOT_PERMITTED

**Comment by birdofpreyru** [comment]
It is just the app's sandbox blocking Webview from non-encrypted communications. You can broadly allow it [this way](https://github.com/birdofpreyru/react-native-static-server/blob/142ededf6429ff183ad603891069c6894064d5e6/example/android/app/src/main/AndroidManifest.xml#L19), or configured in a more fine-tuned way.

Please, the next time google first before opening a new ticket.
