### ISSUE TITLE
Hosting offline on Android doesn't work

### ISSUE THREAD

**Issue by CaiqueNds** [birdofpreyru/react-native-static-server#87]
If I turn off mobile data and/or WiFi, loading of hosted information does not work on Android, it only works on iOS

**Comment by birdofpreyru** [comment]
Does not happen to me with the [example app](https://github.com/birdofpreyru/react-native-static-server/tree/master/example) &mdash; I just double-checked, ran it in simulator with airplane mode on, and it works as usual. Most probably, you are doing something wrong.
