### ISSUE TITLE
FR: Option to include mod_rewrite for client side routing

### ISSUE THREAD

**Issue by membla** [birdofpreyru/react-native-static-server#88]
For client side routing it would be great if `mod_rewrite` could be included in the build – because I assume there is no any other way with the current set of modules to support client side routing?

Thank you for this fork!

**Comment by birdofpreyru** [comment]
Ok @membla , I'll look into including `mod_rewrite` this week.

**Comment by birdofpreyru** [comment]
Hey @membla , with just released **v0.9.2** [mod_rewrite] should work on all platforms. I saw you made me a donation via GitHub.Sponsors. Thanks! :partying_face: I'll look into mentioning it in README shortly, if you don't mind.

[mod_rewrite]: https://github.com/birdofpreyru/react-native-static-server#enabling-rewrite-module

**Comment by membla** [comment]
Thanks a lot @birdofpreyru – works like it should!
