### ISSUE TITLE
ld: error: --fix-cortex-a53-843419 is only supported on AArch64 targets

### ISSUE THREAD

**Issue by the-unknown** [birdofpreyru/react-native-static-server#92]
I am trying to build the static server and it used to work before.
But I just upgraded to Debian 12 and now this error happens on build:

```
ld: error: --fix-cortex-a53-843419 is only supported on AArch64 targets
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.
  
  C++ build system [build] failed while executing:
      /home/user/Android/Sdk/cmake/3.22.1/bin/ninja \
        -C \
        /home/user/Arbeit/change/test/test-expo/node_modules/@dr.pogodin/react-native-static-server/android/.cxx/Debug/6e76il5i/arm64-v8a \
        lighttpd
    from /home/user/Arbeit/change/test/test-expo/node_modules/@dr.pogodin/react-native-static-server/android
```

**Comment by birdofpreyru** [comment]
Hmm... I saw such error in past... something isn't getting built or linked for the correct architecture. Be sure to try a completely clean build, using RN 0.72 (just in case you are trying it with RN 0.73 &mdash; I haven't tried that yet [#91]), and if nothing helps, please dig up more detailed logs from the failure. And, yeah, I don't officially support Expo &mdash; maybe try first with bare RN?

**Comment by the-unknown** [comment]
I tested with a clean project. 
I found that the error shows up with version 0.9.0.
It disappears with version 0.9.2. So upgrading to version 0.9.2 fixed the issue.

**Comment by birdofpreyru** [comment]
Awesome!
