### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by jmom14** [birdofpreyru/react-native-static-server#93]
code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: StaticServerProject@0.0.1
npm ERR! Found: react-native@0.72.0
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.72.0" from the root project
npm ERR!   peer react-native@"*" from @dr.pogodin/react-native-static-server@0.9.2
npm ERR!   node_modules/@dr.pogodin/react-native-static-server
npm ERR!     @dr.pogodin/react-native-static-server@"^0.9.2" from the root project
npm ERR!   1 more (@dr.pogodin/react-native-fs)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.72.6" from react-native-windows@0.72.22
npm ERR! node_modules/react-native-windows
npm ERR!   peer react-native-windows@"*" from @dr.pogodin/react-native-static-server@0.9.2
npm ERR!   node_modules/@dr.pogodin/react-native-static-server
npm ERR!     @dr.pogodin/react-native-static-server@"^0.9.2" from the root project
npm ERR!   peer react-native-windows@"^0.72" from @dr.pogodin/react-native-fs@2.21.0-alpha.8
npm ERR!   node_modules/@dr.pogodin/react-native-fs
npm ERR!     peer @dr.pogodin/react-native-fs@">=2.21.0-alpha.1" from @dr.pogodin/react-native-static-server@0.9.2
npm ERR!     node_modules/@dr.pogodin/react-native-static-server
npm ERR!       @dr.pogodin/react-native-static-server@"^0.9.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

getting this using react native 0.72.0 and 0.73.0 

npx react-native@latest init StaticServerProject
npm i @dr.pogodin/react-native-static-server

**Comment by birdofpreyru** [comment]
I guess, it should work fine with RN 0.72.7. Library upgrade for RN 0.73 is still pending (#91), and it looks like RN less than 0.72.6 is forbidden by peer deps declarations (though, might still work if forced by `npm install --force`).
