### ISSUE TITLE
[RN v0.73][New Arch][iOS] Example App has issues because of `react-native-webview`

### ISSUE THREAD

**Issue by birdofpreyru** [birdofpreyru/react-native-static-server#94]
See https://github.com/react-native-webview/react-native-webview/issues/3263

This blocks testing of `react-native-static-server` for RN v0.73 / New Arch / iOS.

**Comment by birdofpreyru** [comment]
Fixed in [rn-webview@13.6.4](https://github.com/react-native-webview/react-native-webview/releases/tag/v13.6.4)?

**Comment by birdofpreyru** [comment]
Tested with [react-native-webview@13.6.4](https://github.com/react-native-webview/react-native-webview/releases/tag/v13.6.4) &mdash; the example app build for RN@0.73.1 / iOS / new arch now passes, and all works fine in dev mode, however in release mode the app just shows an empty screen. Haven't dug further into it, but perhaps a react-native-webview issue, and the react-native-static-server library works. Should be further investigated later.

**Comment by iSuslov** [comment]
> Tested with [react-native-webview@13.6.4](https://github.com/react-native-webview/react-native-webview/releases/tag/v13.6.4) — the example app build for RN@0.73.1 / iOS / new arch now passes, and all works fine in dev mode, however in release mode the app just shows an empty screen. Haven't dug further into it, but perhaps a react-native-webview issue, and the react-native-static-server library works. Should be further investigated later.

Possibly related: https://github.com/react-native-webview/react-native-webview/pull/3296

**Comment by birdofpreyru** [comment]
Fixed as of `react-native-webview@13.8.1`.
